"""Add species catalog.

Revision ID: 20260709_0005
Revises: 20260709_0004
Create Date: 2026-07-09
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal

from alembic import op
import sqlalchemy as sa


revision = "20260709_0005"
down_revision = "20260709_0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "species_catalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("common_name", sa.String(length=120), nullable=False),
        sa.Column("scientific_name", sa.String(length=160), nullable=True),
        sa.Column("family", sa.String(length=120), nullable=True),
        sa.Column("care_level", sa.String(length=40), nullable=True),
        sa.Column("temperament", sa.String(length=80), nullable=True),
        sa.Column("min_tank_liters", sa.Numeric(8, 2), nullable=True),
        sa.Column("temperature_min_f", sa.Numeric(5, 2), nullable=True),
        sa.Column("temperature_max_f", sa.Numeric(5, 2), nullable=True),
        sa.Column("ph_min", sa.Numeric(4, 2), nullable=True),
        sa.Column("ph_max", sa.Numeric(4, 2), nullable=True),
        sa.Column("social_group_min", sa.Integer(), nullable=True),
        sa.Column("light_requirement", sa.String(length=40), nullable=True),
        sa.Column("co2_recommended", sa.Boolean(), nullable=False),
        sa.Column("fertilizer_relevant", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("external_refs", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "category", "scientific_name", name="uq_species_catalog_category_species"
        ),
    )
    op.create_index(
        "ix_species_catalog_category_common",
        "species_catalog",
        ["category", "common_name"],
        unique=False,
    )
    op.create_index(op.f("ix_species_catalog_category"), "species_catalog", ["category"])
    op.create_index(op.f("ix_species_catalog_common_name"), "species_catalog", ["common_name"])
    op.create_index(
        op.f("ix_species_catalog_scientific_name"),
        "species_catalog",
        ["scientific_name"],
    )

    op.create_table(
        "species_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_entry_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=160), nullable=False),
        sa.Column("alias_type", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["catalog_entry_id"], ["species_catalog.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("catalog_entry_id", "alias", name="uq_species_alias_entry_alias"),
    )
    op.create_index(op.f("ix_species_aliases_alias"), "species_aliases", ["alias"])
    op.create_index(
        op.f("ix_species_aliases_catalog_entry_id"),
        "species_aliases",
        ["catalog_entry_id"],
    )

    with op.batch_alter_table("livestock") as batch_op:
        batch_op.add_column(sa.Column("species_catalog_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_livestock_species_catalog_id",
            "species_catalog",
            ["species_catalog_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_index(op.f("ix_livestock_species_catalog_id"), ["species_catalog_id"])

    with op.batch_alter_table("plants") as batch_op:
        batch_op.add_column(sa.Column("species_catalog_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_plants_species_catalog_id",
            "species_catalog",
            ["species_catalog_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_index(op.f("ix_plants_species_catalog_id"), ["species_catalog_id"])

    _seed_species_catalog()


def downgrade() -> None:
    with op.batch_alter_table("plants") as batch_op:
        batch_op.drop_index(op.f("ix_plants_species_catalog_id"))
        batch_op.drop_constraint("fk_plants_species_catalog_id", type_="foreignkey")
        batch_op.drop_column("species_catalog_id")

    with op.batch_alter_table("livestock") as batch_op:
        batch_op.drop_index(op.f("ix_livestock_species_catalog_id"))
        batch_op.drop_constraint("fk_livestock_species_catalog_id", type_="foreignkey")
        batch_op.drop_column("species_catalog_id")
    op.drop_index(op.f("ix_species_aliases_catalog_entry_id"), table_name="species_aliases")
    op.drop_index(op.f("ix_species_aliases_alias"), table_name="species_aliases")
    op.drop_table("species_aliases")
    op.drop_index(op.f("ix_species_catalog_scientific_name"), table_name="species_catalog")
    op.drop_index(op.f("ix_species_catalog_common_name"), table_name="species_catalog")
    op.drop_index(op.f("ix_species_catalog_category"), table_name="species_catalog")
    op.drop_index("ix_species_catalog_category_common", table_name="species_catalog")
    op.drop_table("species_catalog")


def _seed_species_catalog() -> None:
    species_catalog = sa.table(
        "species_catalog",
        sa.column("id", sa.Integer),
        sa.column("category", sa.String),
        sa.column("common_name", sa.String),
        sa.column("scientific_name", sa.String),
        sa.column("family", sa.String),
        sa.column("care_level", sa.String),
        sa.column("temperament", sa.String),
        sa.column("min_tank_liters", sa.Numeric),
        sa.column("temperature_min_f", sa.Numeric),
        sa.column("temperature_max_f", sa.Numeric),
        sa.column("ph_min", sa.Numeric),
        sa.column("ph_max", sa.Numeric),
        sa.column("social_group_min", sa.Integer),
        sa.column("light_requirement", sa.String),
        sa.column("co2_recommended", sa.Boolean),
        sa.column("fertilizer_relevant", sa.Boolean),
        sa.column("notes", sa.Text),
        sa.column("source", sa.String),
        sa.column("is_builtin", sa.Boolean),
        sa.column("external_refs", sa.JSON),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )
    now = datetime.utcnow()
    op.bulk_insert(
        species_catalog,
        [
            _row(
                1,
                "fish",
                "Neon Tetra",
                "Paracheirodon innesi",
                "Characidae",
                "beginner",
                "peaceful",
                38,
                70,
                81,
                "6.0",
                "7.5",
                6,
                notes="Classic schooling community fish.",
                now=now,
            ),
            _row(
                2,
                "fish",
                "Cardinal Tetra",
                "Paracheirodon axelrodi",
                "Characidae",
                "intermediate",
                "peaceful",
                57,
                73,
                82,
                "4.5",
                "7.0",
                6,
                notes="Best in mature, stable aquariums.",
                now=now,
            ),
            _row(
                3,
                "fish",
                "Betta",
                "Betta splendens",
                "Osphronemidae",
                "beginner",
                "semi-aggressive",
                19,
                76,
                82,
                "6.5",
                "7.5",
                1,
                notes="Usually kept singly, especially males.",
                now=now,
            ),
            _row(
                4,
                "fish",
                "Guppy",
                "Poecilia reticulata",
                "Poeciliidae",
                "beginner",
                "peaceful",
                38,
                72,
                82,
                "6.8",
                "7.8",
                3,
                notes="Hardy livebearer; population can grow quickly.",
                now=now,
            ),
            _row(
                5,
                "fish",
                "Zebra Danio",
                "Danio rerio",
                "Danionidae",
                "beginner",
                "active",
                38,
                64,
                75,
                "6.5",
                "7.5",
                6,
                notes="Active schooling fish for cooler community tanks.",
                now=now,
            ),
            _row(
                6,
                "fish",
                "Peppered Cory",
                "Corydoras paleatus",
                "Callichthyidae",
                "beginner",
                "peaceful",
                76,
                72,
                79,
                "6.0",
                "7.5",
                6,
                notes="Bottom-dwelling social catfish.",
                now=now,
            ),
            _row(
                7,
                "fish",
                "Harlequin Rasbora",
                "Trigonostigma heteromorpha",
                "Danionidae",
                "beginner",
                "peaceful",
                38,
                72,
                81,
                "6.0",
                "7.5",
                6,
                notes="Reliable schooling fish for planted aquariums.",
                now=now,
            ),
            _row(
                8,
                "fish",
                "Cherry Barb",
                "Puntius titteya",
                "Cyprinidae",
                "beginner",
                "peaceful",
                76,
                73,
                81,
                "6.0",
                "7.5",
                6,
                notes="Colorful, generally peaceful barb.",
                now=now,
            ),
            _row(
                9,
                "fish",
                "Dwarf Gourami",
                "Trichogaster lalius",
                "Osphronemidae",
                "intermediate",
                "semi-aggressive",
                38,
                72,
                82,
                "6.0",
                "7.8",
                1,
                notes="Colorful centerpiece fish for calm tanks.",
                now=now,
            ),
            _row(
                10,
                "fish",
                "Otocinclus",
                "Otocinclus macrospilus",
                "Loricariidae",
                "intermediate",
                "peaceful",
                76,
                72,
                79,
                "6.5",
                "7.5",
                6,
                notes="Best added to mature tanks with biofilm.",
                now=now,
            ),
            _row(
                11,
                "invertebrate",
                "Amano Shrimp",
                "Caridina multidentata",
                "Atyidae",
                "beginner",
                "peaceful",
                19,
                65,
                80,
                "6.5",
                "8.0",
                3,
                notes="Useful algae grazer; larvae require brackish water.",
                now=now,
            ),
            _row(
                12,
                "invertebrate",
                "Cherry Shrimp",
                "Neocaridina davidi",
                "Atyidae",
                "beginner",
                "peaceful",
                19,
                64,
                78,
                "6.5",
                "8.0",
                10,
                notes="Hardy dwarf shrimp with many color morphs.",
                now=now,
            ),
            _row(
                13,
                "invertebrate",
                "Nerite Snail",
                "Neritina natalensis",
                "Neritidae",
                "beginner",
                "peaceful",
                19,
                72,
                78,
                "7.0",
                "8.5",
                1,
                notes="Algae-grazing snail; eggs do not hatch in freshwater.",
                now=now,
            ),
            _row(
                14,
                "invertebrate",
                "Mystery Snail",
                "Pomacea diffusa",
                "Ampullariidae",
                "beginner",
                "peaceful",
                38,
                68,
                82,
                "7.0",
                "8.4",
                1,
                notes="Large freshwater snail; benefits from calcium-rich water.",
                now=now,
            ),
            _row(
                101,
                "plant",
                "Java Fern",
                "Microsorum pteropus",
                "Polypodiaceae",
                "beginner",
                None,
                None,
                68,
                82,
                "6.0",
                "8.0",
                None,
                "low",
                False,
                False,
                "Attach rhizome to hardscape; do not bury.",
                now=now,
            ),
            _row(
                102,
                "plant",
                "Anubias",
                "Anubias barteri",
                "Araceae",
                "beginner",
                None,
                None,
                72,
                82,
                "6.0",
                "8.0",
                None,
                "low",
                False,
                False,
                "Slow grower; attach rhizome to rock or wood.",
                now=now,
            ),
            _row(
                103,
                "plant",
                "Amazon Sword",
                "Echinodorus grisebachii",
                "Alismataceae",
                "beginner",
                None,
                None,
                72,
                82,
                "6.5",
                "7.8",
                None,
                "medium",
                False,
                True,
                "Heavy root feeder; root tabs are useful.",
                now=now,
            ),
            _row(
                104,
                "plant",
                "Crypt Wendtii",
                "Cryptocoryne wendtii",
                "Araceae",
                "beginner",
                None,
                None,
                72,
                82,
                "6.0",
                "7.8",
                None,
                "low",
                False,
                True,
                "Root feeder that may melt after changes, then recover.",
                now=now,
            ),
            _row(
                105,
                "plant",
                "Java Moss",
                "Taxiphyllum barbieri",
                "Hypnaceae",
                "beginner",
                None,
                None,
                64,
                82,
                "5.5",
                "8.0",
                None,
                "low",
                False,
                False,
                "Hardy moss for fry and shrimp cover.",
                now=now,
            ),
            _row(
                106,
                "plant",
                "Hornwort",
                "Ceratophyllum demersum",
                "Ceratophyllaceae",
                "beginner",
                None,
                None,
                59,
                86,
                "6.0",
                "8.0",
                None,
                "low",
                False,
                False,
                "Fast-growing stem plant that can float or be planted.",
                now=now,
            ),
            _row(
                107,
                "plant",
                "Water Wisteria",
                "Hygrophila difformis",
                "Acanthaceae",
                "beginner",
                None,
                None,
                70,
                82,
                "6.5",
                "7.8",
                None,
                "medium",
                False,
                True,
                "Fast grower that benefits from regular nutrients.",
                now=now,
            ),
            _row(
                108,
                "plant",
                "Vallisneria",
                "Vallisneria americana",
                "Hydrocharitaceae",
                "beginner",
                None,
                None,
                68,
                82,
                "6.5",
                "8.0",
                None,
                "medium",
                False,
                True,
                "Root-feeding grasslike plant that spreads by runners.",
                now=now,
            ),
            _row(
                109,
                "plant",
                "Dwarf Hairgrass",
                "Eleocharis parvula",
                "Cyperaceae",
                "advanced",
                None,
                None,
                68,
                82,
                "6.5",
                "7.5",
                None,
                "high",
                True,
                True,
                "Carpeting plant; best with strong light and CO2.",
                now=now,
            ),
            _row(
                110,
                "plant",
                "Rotala Rotundifolia",
                "Rotala rotundifolia",
                "Lythraceae",
                "intermediate",
                None,
                None,
                68,
                82,
                "5.5",
                "7.5",
                None,
                "medium",
                True,
                True,
                "Stem plant with better color under higher light.",
                now=now,
            ),
            _row(
                111,
                "plant",
                "Amazon Frogbit",
                "Limnobium laevigatum",
                "Hydrocharitaceae",
                "beginner",
                None,
                None,
                64,
                82,
                "6.0",
                "7.8",
                None,
                "medium",
                False,
                True,
                "Floating plant with dangling roots and fast nutrient uptake.",
                now=now,
            ),
            _row(
                112,
                "plant",
                "Bacopa",
                "Bacopa caroliniana",
                "Plantaginaceae",
                "beginner",
                None,
                None,
                68,
                82,
                "6.0",
                "8.0",
                None,
                "medium",
                False,
                True,
                "Hardy stem plant; trims and replants easily.",
                now=now,
            ),
        ],
    )


def _row(
    id_: int,
    category: str,
    common_name: str,
    scientific_name: str,
    family: str,
    care_level: str,
    temperament: str | None,
    min_tank_liters: int | None,
    temperature_min_f: int,
    temperature_max_f: int,
    ph_min: str,
    ph_max: str,
    social_group_min: int | None,
    light_requirement: str | None = None,
    co2_recommended: bool = False,
    fertilizer_relevant: bool = False,
    notes: str | None = None,
    *,
    now: datetime,
) -> dict:
    return {
        "id": id_,
        "category": category,
        "common_name": common_name,
        "scientific_name": scientific_name,
        "family": family,
        "care_level": care_level,
        "temperament": temperament,
        "min_tank_liters": Decimal(str(min_tank_liters)) if min_tank_liters is not None else None,
        "temperature_min_f": Decimal(str(temperature_min_f)),
        "temperature_max_f": Decimal(str(temperature_max_f)),
        "ph_min": Decimal(ph_min),
        "ph_max": Decimal(ph_max),
        "social_group_min": social_group_min,
        "light_requirement": light_requirement,
        "co2_recommended": co2_recommended,
        "fertilizer_relevant": fertilizer_relevant,
        "notes": notes,
        "source": "builtin",
        "is_builtin": True,
        "external_refs": {},
        "created_at": now,
        "updated_at": now,
    }
